### ISSUE TITLE
Difference of state machine between code implementation and paper?

### ISSUE THREAD

**Issue by cybisolated** [BraveGroup/SheetCopilot#3]
Dear authors, thanks for opening source an implementation of agent. I have tried to run the code, however, when GPT gives an incorrect action in state 1, the state jumps to state "invalid_api", and then just jumps to state "fail", terminating the process. The procedure seems inconsistent with your paper? Looking forward to your reply!

**Comment by ZJULiHongxin** [comment]
Dear user,

Thank you for your interest in SheetCopilot and for sharing your experience with our current release. @cybisolated 

As outlined in the [SheetCopilot Usage](https://github.com/BraveGroup/SheetCopilot#sheetcopilot-usage) section, we have made a **simplified version** of SheetCopilot available, which includes the Chain of Thought (CoT) and document retrieval functionalities.

We understand and acknowledge your eagerness to access the full codebase. At present, we're investigating the traceback effect so we decided not to release this module temporarily. **We add this to our ToDo list and will fully release our code in the future.**

Nevertheless, we encourage our users to implement the unreleased parts of the project (i.e. _error restoration_), which is straightforward.

Please rest assured that fully open-sourcing SheetCopilot remains a priority for us. We aim to release the complete, refined code as soon as we have completed our further research.

We appreciate your involvement. Do continue to share your feedback and suggestions with us.

Warm regards,

SheetCopilot Team

**Comment by cybisolated** [comment]
I understand your point and look forward to your follow-ups. Thanks again for your reply and work!

**Comment by ZJULiHongxin** [comment]
@cybisolated We have released the full SheetCopilot agent used in our NeurIPS'23 paper. Thank you for using our agent!
